version: 2
sources:
   - name: raw # allias de la table
     schema: gz_raw_data #Nom exact du dataset dans BQ
     description: greenwez raw data source
     tables:
         - name: sales # allias de la table
           identifier: raw_gz_sales #Nom exact de la table dans BQ
           description: sales of greewneez / we have one row per product_id found in each order_id
           loaded_at_field: "CAST(date_date AS TIMESTAMP)"
           freshness: 
             warn_after:
               count: 90
               period: day
           
           columns:
             - name: "(date_date || '_' || orders_id || '-' || pdt_id)"
               description: primary key of the table
               tests:
                 - unique
                 - not_null
         - name: product
           identifier: raw_gz_product
           description: purchase_price by products_id
           columns:
             - name: products_id
               description: primary key of the table
               tests:
                 - unique
                 - not_null
         - name: ship
           identifier: raw_gz_ship
           description: ship and log costs by orders_id
           columns:
             - name: orders_id
               description: primary key of the table
               tests:
                 - unique
                 - not_null
         - name: adwords
           identifier: raw_gz_adwords
           description: data about the adwords ads campaign
           columns:
             - name: date_date
               description: launch date of the campaign
               tests:
                 - not_null
             - name: paid_source
               description: Entreprise paid to publish ads
               tests:
                 - not_null
             - name: campaign_key
               description: Identification key of the campaign
               tests:
                 - not_null
             - name: ads_cost
               description: cost to publish ads
               tests:
                 - not_null
             - name: impression
               description: number of impressions
               tests:
                 - not_null
             - name: click
               description: number of clicks on the ad
               tests:
                 - not_null
         - name: bing
           identifier: raw_gz_bing
           description: data about the bing ads campaign
           columns:
             - name: date_date
               description: launch date of the campaign
               tests:
                 - not_null
             - name: paid_source
               description: Entreprise paid to publish ads
               tests:
                 - not_null
             - name: campaign_key
               description: Identification key of the campaign
               tests:
                 - not_null
             - name: ads_cost
               description: cost to publish ads
               tests:
                 - not_null
             - name: impression
               description: number of impressions
               tests:
                 - not_null
             - name: click
               description: number of clicks on the ad
               tests:
                 - not_null
         - name: criteo
           identifier: raw_gz_criteo
           description: data about the criteo ads campaign
           columns:
             - name: date_date
               description: launch date of the campaign
               tests:
                 - not_null
             - name: paid_source
               description: Entreprise paid to publish ads
               tests:
                 - not_null
             - name: campaign_key
               description: Identification key of the campaign
               tests:
                 - not_null
             - name: ads_cost
               description: cost to publish ads
               tests:
                 - not_null
             - name: impression
               description: number of impressions
               tests:
                 - not_null
             - name: click
               description: number of clicks on the ad
               tests:
                 - not_null
         - name: facebook
           identifier: raw_gz_facebook
           description: data about the facebook ads campaign
           columns:
             - name: date_date
               description: launch date of the campaign
               tests:
                 - not_null
             - name: paid_source
               description: Entreprise paid to publish ads
               tests:
                 - not_null
             - name: campaign_key
               description: Identification key of the campaign
               tests:
                 - not_null
             - name: ads_cost
               description: cost to publish ads
               tests:
                 - not_null
             - name: impression
               description: number of impressions
               tests:
                 - not_null
             - name: click
               description: number of clicks on the ad
               tests:
                 - not_null

models:
   - name: int_orders_margin
     description: Margin per order
     columns:
       - name: orders_id
         description: primary key of the table
         tests:
           - not_null
           - unique
   - name: int_sales_margin
     description: margin per products
     columns:
       - name: "(orders_id || '-' || products_id)"
         description: primary key of the table
         tests:
           - not_null
           - unique
   - name: int_orders_operational
     description: operational margin per orders
     columns:
       - name: orders_id
         description: primary key of the table
         tests:
           - not_null
           - unique
   - name: mrt_finance_days
     description: all finance kpi per day
     columns:
       - name: date_date
         description: primary key of the table
         tests:
           - not_null
           - unique
   - name: int_campaigns
     description: data about the different ads campaign
     columns:
       - name: date_date
         description: launch date of the campaign
         tests:
            - not_null
       - name: paid_source
         description: Entreprise paid to publish ads
         tests:
            - not_null
       - name: campaign_key
         description: Identification key of the campaign
         tests:
            - not_null
       - name: "(date_date || '_' || campaign_key || '-' || campaign_name)"
         description: primary key of the table
         tests:
            - not_null
            - unique
       - name: ads_cost
         description: cost to publish ads
         tests:
            - not_null
       - name: impression
         description: number of impressions
         tests:
            - not_null
       - name: click
         description: number of clicks on the ad
         tests:
            - not_null